# Generated by Django 4.2.1 on 2023-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('image_path', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
